### ISSUE TITLE
Update docs for kv plugin

### ISSUE THREAD

**Issue by arku31** [spiral/roadrunner-docs#85]
On this [page](https://roadrunner.dev/docs/beep-beep-kv) it is saying that we should use the following structure

```
kv:
  redis:
    driver: redis
    addrs:
      - "localhost:6379"

````

but at least for 2.6.3 it has to be under `config:` section - https://github.com/spiral/roadrunner-binary/blob/master/.rr.yaml#L307
